events {
}
http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	server {
		# Listen for HTTPS connections on port 443.
		listen 443 ssl;

		# Define the domain name handled by this server.
		server_name jpiquet.42.fr;

		# Specify the TLS certificate and private key used to secure HTTPS connections.
		ssl_certificate /run/secrets/inception.crt;
		ssl_certificate_key /run/secrets/inception.key;

		# Allow only the TLS protocols required by the subject.
		ssl_protocols TLSv1.2 TLSv1.3;

		# The WordPress volume is mounted at this location.
		# NGINX will use this directory to find the requested website files.
		root /var/www/html;

		# Define index.php as the default file when a directory is requested.
		index index.php index.html;
		
		# Match requests whose URL ends with ".php".
		location ~ \.php$ {

			# Load the standard FastCGI parameters required to communicate with PHP-FPM.
			include fastcgi_params;
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;

			# Tell PHP-FPM the complete path of the PHP script to execute.
			# $document_root is /var/www/html and $fastcgi_script_name is the requested PHP file.
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
