events {
}
http {
	server {
		# On dit qu'on va ecouté sur le port 443 (HTTPS) et qu'il va falloir chiffrer toutes les connexion sur le port.
		listen 443 ssl;
		server_name jpiquet.42.fr;
		
		# On indique ou se trouve les fichiers du certificat et on autorise seulement
		# les protocols ssl demandé par le sujet
		ssl_certificate /etc/ssl/certs/inception.crt;
		ssl_certificate_key /etc/ssl/private/inception.key;
		ssl_protocols TLSv1.2 TLSv1.3;
		
		# Le volume WordPress sera monté dans ce dossier donc on indique a nginx 
		# ou est ce qu'il devra cherché les fichiers lorsque le navigateur lui demandera.
		root /var/www/html;

		index index.php


