#version: "3"
#name: Inception

#volumes:
#  wordpress:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/jocelyn/data/wordpress
#  mariadb:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/jocelyn/data/mariadb

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    volumes:
      - /home/jocelyn/data/wordpress:/var/www/html
#      - wordpress:/var/www/html
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - /home/jocelyn/data/wordpress:/var/www/html
#      - wordpress:/var/www/html
    expose:
      - 9000
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - /home/jocelyn/data/mariadb:/var/lib/mysql
#     - mariadb:/var/lib/mysql
    expose:
      - 3306
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge
