#version: "3"
#name: Inception

services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    expose:
      - 9000
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - user_password
      - admin_password
    networks:
      - inception
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "healthcheck" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    restart: always
    init: true

secrets:
  db_password:
    file: /home/${USER}/Inception/secrets/db_password.txt
  db_root_password:
    file: /home/${USER}/Inception/secrets/db_root_password.txt
  admin_password:
    file: /home/${USER}/Inception/secrets/admin_password.txt
  user_password:
    file: /home/${USER}/Inception/secrets/user_password.txt

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
