name: Inception

services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - /home/login/data/wordpress:/var/www/html
    expose:
      - 9000
    depends_on:
      - mariadb
    env file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - /home/login/data/mariadb:/var/lib/mysql
    expose:
      - 3306
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
